### PR TITLE
GCC webhook

### PR DESCRIPTION
**Pull request by wm75**
The webhook generates an iframe to https://galaxyproject.org/events/gcc2019/ subpages and a link to the training vote page

### CODE REVIEW

**Comment by wm75** [comment]
screenshot from 2019-01-29 13-30-22

**Comment by wm75** [comment]
image

**Comment by wm75** [comment]
two example screenshots showing the thing in action after job submission

**Comment by hexylena** [comment]
Can you just add the URLs to the existing iframe plugin please?

**Comment by wm75** [comment]
I could, but @bebatut asked me to do this with the idea of promoting voting for trainings. That is, this is not just about adding additional iframes to the existing webhook, but also to have a title with vote announcement that stands out.
I imagine this webhook to be shown to users at high frequency and to use it over the coming months to announce deadlines for registration, abstract submission, _etc_, so I think just adding the links to *iframe* misses an important point.
What I could do though is to backport my fixes from this webhook to *iframe* to make it functional again (at  least, I had to make small changes to get it running in my local instance and I don't remember seeing any of these iframes over the past months on the server either).

**Comment by bgruening** [comment]
> local instance and I don't remember seeing any of these iframes over the past months on the server either).

Oh, ok its not me. I added links actually on monday to our iframe webhook, but I also never saw it.

**Comment by wm75** [comment]
issues with the iframe webhook (at least when using it locally and as far as I remember):
https://github.com/usegalaxy-eu/galaxy/blob/55be9e3c8f6409953ab5869891930e609e12e3e5/config/plugins/webhooks/iframe/script.js#L24

`/get_data` in the query address does not seem to work (had to change it to `/data`)

https://github.com/usegalaxy-eu/galaxy/blob/55be9e3c8f6409953ab5869891930e609e12e3e5/config/plugins/webhooks/iframe/script.js#L32

had to remove the parentheses here

**Comment by hexylena** [comment]
> have a title with vote announcement that stands out.

I had not seen that the title was part of that, it originally looked from the screenshots like it was part of the google form.

I would remove "Vote for your favourite training HERE & NOW" and just replace that with the "Freiburg, Germany" from the title + add "Vote now!" the here/capitalisation is strange.

> I imagine this webhook to be shown to users at high frequency and to use it over the coming months to announce deadlines for registration, abstract submission, etc, so I think just adding the links to iframe misses an important point.

We cannot control the frequency at which individual webhooks are shown, we can only control the frequency of URLs selected within the iframe.

By keeping it separate, you're ensuring that the maximum number of times GCC things can be shown is *strictly lower* than if you merged them, where we could hide the other URLs at some point.

Can you please just merge the two? Support setting the big fancy titles in the original / replace the original with the new one and add in the old URLs with appropriate titles?

> What I could do though is to backport my fixes from this webhook to iframe to make it functional again

Yes. Please do that. The next time you notice something is broken like this, then, please file an issue or just patch it. It takes a village to maintain .eu and I don't run jobs often enough to notice that the news webhook is missing.

**Comment by wm75** [comment]
> We cannot control the frequency at which individual webhooks are shown, we can only control the frequency of URLs selected within the iframe.
> 
> By keeping it separate, you're ensuring that the maximum number of times GCC things can be shown is _strictly lower_ than if you merged them, where we could hide the other URLs at some point.

I thought it would be easier to disable webhooks temporarily to give priority to others, than to disable/enable individual links within one webhook, but that's up to you.

I'll try to merge them later.

**Comment by hexylena** [comment]
I seem to have mis-remembered using a weighted choice,hmm.

If you merge them now, I'll add that later, and we'll have a sum total better outcome. Thanks for merging! Then you can have even more control over which webhooks are shown more/less.

**Comment by wm75** [comment]
reenables the iframe webhook and shows GCC announcements occasionally (about every second time the iframe webhook is chosen).

**Comment by hexylena** [comment]
```
$ for i in {1..100}; do python ./config/plugins/webhooks/iframe/__init__.py | jq .title>> tmp; done;
$ cat tmp | sort | uniq -c
      8 "Galactic News"
     33 "Galaxy Community Conference 2019 - Freiburg, Germany"
     24 "Galaxy Community Conference 2019 - Training Topics"
     18 "Galaxy Community Conference 2019 - Vote on Trainings"
      8 "Galaxy Queue (past 3 hours)"
      9 "Upcoming Events"
```

can play with probabilities as time goes on.

**Comment by hexylena** [comment]
Thanks so much @wm75

**Pull request merged**
