### PR TITLE
Add DIVAnd interactive tool

### PR DESCRIPTION
**Pull request by Marie59**
Initiating the PR for DIVAnd interactive tool. A new tool for divand jupyterlab and notebooks on coastal water dynamics.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

### CODE REVIEW

**Comment by bgruening** [comment]
When do you need that @Marie59 ?

**Comment by Marie59** [comment]
> When do you need that @Marie59 ?

As soon as possible would be great but no pressure (what would be amazing would be to have it ready for the training session or even before) ! But I don't know what you need to do now ? How long is the following process ?

**Comment by bgruening** [comment]
Let me be more concrete to you need it today or is Wednesday next week ok as well? :)

**Comment by Marie59** [comment]
Ooh Wednesday next week is more than perfect !! ;) Thank you !!

**Pull request merged**
