### PR TITLE
Merge release_20.09

### PR DESCRIPTION
**Pull request by OlegZharkov**
Upsteam update

### CODE REVIEW

**Comment by bgruening** [comment]
There is something wrong here I assume. This looks scary :(

**Comment by bgruening** [comment]
@OlegZharkov is this just the upstream update?

**Comment by OlegZharkov** [comment]
> @OlegZharkov is this just the upstream update?

it's ```git merge release_20.09```

I mean it's in the title...

**Comment by gmauro** [comment]
@OlegZharkov can you move to a separate PR the commits that has not been pushed upstream?

**Comment by OlegZharkov** [comment]
> @OlegZharkov can you move to a separate PR the commits that has not been pushed upstream?

yep

**Comment by OlegZharkov** [comment]
thanks @gmauro

**Pull request merged**
