### PR TITLE
Add visualisation for Chimeras

### PR DESCRIPTION
**Pull request by anuprulez**
cv3

cv2

cv1

### CODE REVIEW

**Comment by bgruening** [comment]
Do we need to build the client here?

**Comment by anuprulez** [comment]
I think so. Whenever I update JS files, Galaxy builds the client again and shows a message: 
`The Galaxy client is out of date and will be built now`

**Comment by OlegZharkov** [comment]
@anuprulez @bgruening if you don't want to build the client, you  probably can use 
```cd client && yarn run gulp plugins```

**Comment by bgruening** [comment]
We can build the client, no problem, but we need to push it to this PR. I'm wondering if we need to commit the JS files.

**Pull request merged**
