### PR TITLE
try to fix panoply interactive tool

### PR DESCRIPTION
**Pull request by annefou**
-Define new home for user
- add colorbars.tar for additional colorbars
- All tools outputs should be png files and in output folder.

### CODE REVIEW

**Comment by bgruening** [comment]
@annefou can we put tools/interactive/colorbars.tar  into the container?

**Comment by bgruening** [comment]
There are some whitespace issues ...

**Comment by annefou** [comment]
It did not work. So this is why it is here...

**Comment by bgruening** [comment]
EU can ship it, but if we want to upstream it those things needs to be in a container.

Do you have the error? The tarball could be under /usr/share/... I guess you need to make sure that the permissions are correct.

**Comment by annefou** [comment]
Ok. I'll try again.

**Pull request merged**
