### PR TITLE
Add gapars webhook

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by bgruening** [comment]
Ideally this would only popup after given tools ... mh, or can we restrict it to the ecology subdomain. We should be able to detect the subdomain in JS and do not display anything in case of a different domain, for the time being?

**Comment by hexylena** [comment]
Sure @ only after tools.

For the domain... In that case we should just use the iframe webhook, and not a separate webhook. And we would need to rewrite the webhook to do the URL choosing on the client rather than server side so it can exclude that per domain? Are you concerned about some potential issue?

**Comment by bgruening** [comment]
> For the domain... In that case we should just use the iframe webhook, and not a separate webhook. And we would need to rewrite the webhook to do the URL choosing on the client rather than server side so it can exclude that per domain? Are you concerned about some potential issue?

I think in the long run we need to have a mechanism to whitelist webhooks per domain (or other criteria, like groups/roles etc). Bees should probably not displayed to singlecell people, isn't it?

**Comment by hexylena** [comment]
I can understand wanting that mechanism to "target audiences", but I don't have time currently to write that. Maybe I will file an issue on your projects repo since I can tell how it should be done.

> Bees should probably not displayed to singlecell people, isn't it?

I guess I have a different feeling for this? I'd make the following points:

- It isn't about bees in specific, it's about citizen science in general, about contributing to a project. We should phrase it more as "look what citizen science can do for research", we could easily include links to other european galaxy related CS projects like beer decoded or so.
- As a research scientist/biochemist who likes computers, I've always loved "fold @ home" type projects, where I could contribute to some area of science maybe I don't know as much about, but I still get the good emotions/feeling of "I'm helping science, yeah!!"
- We have a number of users who are learners, if they're just using the singlecell domain (or other), then they get a very restricted view of "what galaxy is". Exposing them to other topics could be good to help them understand that "galaxy isn't just X", galaxy is more than that, it's used for ecology, for imaging, etc.?
- And for the volume of data we can get, citizen science projects like this work best when more people see them and can decide to contribute, we could get people who aren't normally doing ecology to contribute, rather than just restricting it to ecologists who are already doing similar things.
- Do you feel it might negatively affect the experience of singlecell users?

Dunno, those are just my feelings. Even though I'm not an ecologist or bee person, I would absolutely click some bee images between jobs, and it might be more educational/interesting/fun than seeing the events list again.

**Comment by yvanlebras** [comment]
I have to say that @erasche totally perfectly says what is also just my feelings, totally agree with the 4 points, and that's true that for me the major concern is to not negatively affect the experience of singlecell users... I think about that since we begun discussing about that at GCC, and I really don't know of this can be negative to have such "mini games" unrelated to the initial subject of interest of the Galaxy user.... Thank you a lot both for pointing so clearly these important points!

**Comment by hexylena** [comment]
*Received permission in private chat to deploy this.*

**Comment by bgruening** [comment]
Hi, so great this is now merged! Really cool. My comments inline.

Singlecell was just an example. Think about Material Science etc or any other community.
This discussing from my side is not at all in regards to GAPARS, I love it, its more a general concern that we need to extend the framework a little bit.

> It isn't about bees in specific, it's about citizen science in general, about contributing to a project. We should phrase it more as "look what citizen science can do for research", we could easily include links to other european galaxy related CS projects like beer decoded or so.

All my assumptions and my concerns are with a huge amount of webhooks, few or many very specific. People get things to see which they are likely not interested - advertising other communities can still be done with a single link webhook/page or something like that.

I fear that important information do not get to the user, because they are spammed with "unrelated" stuff.

> As a research scientist/biochemist who likes computers, I've always loved "fold @ home" type projects, where I could contribute to some area of science maybe I don't know as much about, but I still get the good emotions/feeling of "I'm helping science, yeah!!"

Sure, but how does this relate to the discussion? Make the webhooks you want to see selectable? So I can only and always see/help to fold-at-home?

> We have a number of users who are learners, if they're just using the singlecell domain (or other), then they get a very restricted view of "what galaxy is". Exposing them to other topics could be good to help them understand that "galaxy isn't just X", galaxy is more than that, it's used for ecology, for imaging, etc.?

The point of these subdomains is to be restricted, if you want to see the entire Galaxy you should and will use usegalaxy.eu. We can hint people once in a while to other areas, but this should be the exception and not the rule imho. Since people explicitly picked that subdomain to not be overwhelemd with other stuff.

> And for the volume of data we can get, citizen science projects like this work best when more people see them and can decide to contribute, we could get people who aren't normally doing ecology to contribute, rather than just restricting it to ecologists who are already doing similar things.

My point is simply scaling in the long run, one or two projects of these kind probably work for all users, but if it get more we should be more flexible in the framework to be smarter in exposing some webhooks to only a part of users. Just imagine 30 different webhooks. The chance that you see the Bee is minimal. But if you the framework is smarter, more users that are maybe even more interested in it, see the Bee more and the end-result is maybe more productive.

> Do you feel it might negatively affect the experience of singlecell users?

No. Its fun as the comics are, even better its more useful than comics ;) But with 20+ webhooks I feel we can and should do better.

**Comment by yvanlebras** [comment]
Hmm, you're right. I was not thinking to the next future and having 3000+ (why not ;) ) different webhooks. True that testing the bee one forced me to send >10 jobs each time to display it on the Galaxy interface and make my screencast.
ITM, this will say there is a need to add webhooks oriented Galaxy functionalities as:
- "eu subdomains webhooks configurator" so we can select which webhooks are of interest + maybe additional things like the frequency and order to display it
- "user webhook configurator" this time oriented towards user preferences
- "access to "standalone" webhook" (through main menu for example) so a Galaxy user can use/play it  without having to submit a job...

Really big thank for making it real and for these exchanges! Now it's alive, I really see interesting next steps I was not thinking about before. A first who comes to my mind is that for GAPARS report, I gave some potential statistics for impact and I was thinking that with a mean of 4000 jobs per day on eu, we potentially can wish up to 4000 classifications. But in fact, waiting for a job to be scheduled then executed can take some times and you can classify 4, 69 bees for a "simple" job...

So I just begin to realise that there is for sure a lot to do and potential incredible outcomes.... Wouhaouhou!

**Pull request merged**
