### PR TITLE
Add VRM Editor interactive tool (Climate) in release 21.01 europe

### PR DESCRIPTION
**Pull request by annefou**
### Interactive Climate Tool for creating Variable Resolution Mesh for NorESM/CESM climate models.

- Docker container is on quay.io (see https://github.com/NordicESMhub/docker-vrm-editor for more information).
- The tool has an optional parameter which is an existing grid or description of a grid. When no parameter is given, one needs to create a new grid from scratch.
- The generated grid is a netCDF file that can be used for running CESM or NorESM climate models.
- I tested the docker container but unfortunately did not manage to test the interactive tool locally with my galaxy test instance.

### CODE REVIEW

**Comment by gmauro** [comment]
@annefou Are you pushing it upstream also?

**Comment by annefou** [comment]
@gmauro What do you mean by upstream? galaxyproject/galaxy? No I didn't. Should I? What is the "standard" way to request changes? Sorry I guess I should know but I don't... I mean I probably forgot or/and did not read the documentation carefuly!

**Comment by gmauro** [comment]
Yes, with upstream I mean galaxyproject/galaxy. Usually, we commit there and backport here, see: #98

**Comment by bgruening** [comment]
I guess we can get this in and Anne can test it?

**Comment by gmauro** [comment]
Yes, sure. I just want to make sure the commit doesn't just stay here

**Comment by gmauro** [comment]
https://github.com/usegalaxy-eu/infrastructure-playbook/commit/34c9ac4f7d2f2cde09f1b048be522e67cd4e9fb1

**Comment by bgruening** [comment]
and https://github.com/usegalaxy-eu/infrastructure-playbook/commit/73ef27d36d8957d70f826a7b2001dc3401920d42

**Pull request merged**
