### PR TITLE
Tool recommendation patch

### PR DESCRIPTION
**Pull request by anuprulez**
This PR adds these features:
- Add an API test
- Allow addition of tools recommended by a Galaxy admin
- Show more recommended tools and allow scroll in the modal popup
- Fix a few bugs (recommended tools are filtered by datatype constraints and workflow connections)

### CODE REVIEW

**Comment by hexylena** [comment]
This looks strange, could you please rebase your work on a more recent copy of the `release_19.09_europe` branch?

**Comment by anuprulez** [comment]
release_19.09_europe > tool_recommendation_datatypes_fix

https://github.com/usegalaxy-eu/galaxy/compare/release_19.09_europe...usegalaxy-eu:tool_recommendation_datatypes_fix?expand=1

It just shows some extra commits.

**Comment by hexylena** [comment]
It looks like more than just showing duplicated commits, this includes openlayers and changes to the blastdb.loc.sample? And a rebuild of the client among other things? 

I can rebase and push to this branch.

**Comment by bgruening** [comment]
@anuprulez can you please rebase your PR? Thanks!

**Comment by anuprulez** [comment]
Moved to PR: https://github.com/usegalaxy-eu/galaxy/pull/24

**Pull request closed without merging**
