### PR TITLE
add data import

### PR DESCRIPTION
**Pull request by yvanlebras**
I was frogetting the data import part apparently :)

### CODE REVIEW

**Comment by yvanlebras** [comment]
Thank you! Here was a first stupid issue (my fault sorry). In fact there is another issue with geoexplorer and radiant IT who seems to be related to the fact here we create a ln to the Galaxy dataset but for GIE we were copying it so here, the user (shiny) don't have access to datasets... I will look at it

**Comment by yvanlebras** [comment]
On the older GUE manner, we were managing this file access through mako template file : 
```
CNVdata = ie_request.volume(hda.file_name, '/srv/shiny-server/data/inputdata.txt', how='ro')
ie_request.launch(
        volumes=[CNVdata],
        image=trans.request.params.get('image_tag', None),
        env_override={
                'PUB_HOSTNAME': ie_request.attr.HOST,
})
```
From https://github.com/65MO/Galaxy-E/blob/master/GIE/GIE/templates/interactiveShiny.mako

**Comment by bgruening** [comment]
Yes, this is true, please copy. Inside the container the symlink might not be valid. Security concerns.

**Comment by yvanlebras** [comment]
Ok, thank you!!!!!

**Comment by yvanlebras** [comment]
Ok done!

**Pull request merged**
