### PR TITLE
Add bref3 datatype

### PR DESCRIPTION
**Pull request by gallardoalba**
## What did you do? 
- This PR includes the bref3 datatype

## Why did you make this change?
This datatype is required for the Beagle tool https://github.com/galaxyproject/tools-iuc/pull/3760

## How to test the changes? 
(select the most appropriate option; if the latter, provide steps for testing below)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:

>>> from galaxy.datatypes.sniff import get_test_fname
>>> fname = get_test_fname('affy_v_agcc.cel')
>>> Bref3().sniff(fname)
False
>>> fname = get_test_fname('ref.bref3')
>>> Bref3().sniff(fname)
True

## License
- [x] I agree to license these contributions under [Galaxy's current license](https://github.com/galaxyproject/galaxy/blob/dev/LICENSE.txt).
- [x] I agree to allow the Galaxy committers to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT). If this condition is an issue, uncheck and just let us know why with an e-mail to galaxy-committers@lists.galaxyproject.org.

## For UI Components
- [ ] I've included a screenshot of the changes

### CODE REVIEW

**Comment by bgruening** [comment]
@gallardoalba thanks. Can you also add this to the main Galaxy codebase?

**Comment by bgruening** [comment]
If possible to the 21.05 branch.

**Comment by gallardoalba** [comment]
> If possible to the 21.05 branch.

Done https://github.com/galaxyproject/galaxy/pull/12199

**Comment by gmauro** [comment]
fixed upstream

**Pull request closed without merging**
