### PR TITLE
Revert "graphclust tours"

### PR DESCRIPTION
**Pull request by bgruening**
Reverts usegalaxy-eu/galaxy#6

### CODE REVIEW

**Comment by bgruening** [comment]
Damn, @mmiladi this was the wrong branch. You need to take the european 18.09 branch.

**Comment by mmiladi** [comment]
Ow sorry it looked to be the same..
screenshot from 2019-02-02 22-37-12

**Comment by mmiladi** [comment]
Thanks anyway

**Comment by bgruening** [comment]
All good :)

**Pull request merged**
