### PR TITLE
Update askomics IT

### PR DESCRIPTION
**Pull request by abretaud**
Preparing for our BCC training with @xgaia, IIRC we can use usegalaxy.eu for that?
It's the same xml as in https://github.com/galaxyproject/galaxy/pull/9915
Do you plan to do the 20.05 update before or after bcc?
Should we also do a tiass registration or is this done by BCC organisators?

### CODE REVIEW

**Comment by bgruening** [comment]
>  Do you plan to do the 20.05 update before or after bcc?

We could, @gmauro has most of it prepared ... we are not sure if we should ... what do you say?

**Comment by gmauro** [comment]
I think we have enough capacity for Interactive tools and in any case, TIaaS doesn't matter as it uses a different set of nodes.
But I will add more IT enabled nodes before BCC.
I am not aware if BCC organizers are submitting a request for TIaaS, but to stay on the safe side, I suggest to do it by yourself.
https://galaxyproject.eu/tiaas

**Comment by gmauro** [comment]
About the update, I am a bit worried to create "noise"  when all (trainers, speakers, BCC participants) are working on preparing or reviewing datasets, tutorials, procedures...

**Comment by abretaud** [comment]
Ok thanks for the merge and the tiass info :)
We're fine with not updating, I was just wondering if we would need to make a last round of tests before d-day with an updated version

**Pull request merged**
